# Generated by Django 3.2.9 on 2021-11-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_slack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackteam',
            name='info',
            field=models.TextField(null=True, verbose_name='Team Info'),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='info',
            field=models.TextField(null=True, verbose_name='User Info'),
        ),
    ]
