# Generated by Django 3.0.4 on 2020-03-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackusertoken',
            name='team_id',
            field=models.CharField(max_length=1024, null=True, verbose_name='Team ID'),
        ),
        migrations.AddField(
            model_name='slackusertoken',
            name='team_name',
            field=models.CharField(max_length=1024, null=True, verbose_name='Team Name'),
        ),
    ]
